// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfI_VmjnXj1fur9IdwobzmNgGnBlePvl0',
    appId: '1:968848825333:web:92fc35ddd2f525dab45ebc',
    messagingSenderId: '968848825333',
    projectId: 'interview-task-project-97e2d',
    authDomain: 'interview-task-project-97e2d.firebaseapp.com',
    storageBucket: 'interview-task-project-97e2d.appspot.com',
    measurementId: 'G-487M0WSDT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Z2VuwxgLSoDrjAqpTp8yktfttl_z5xk',
    appId: '1:968848825333:android:7bb082bc5a446f13b45ebc',
    messagingSenderId: '968848825333',
    projectId: 'interview-task-project-97e2d',
    storageBucket: 'interview-task-project-97e2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTc-FI5QJvobFGWcyJ28O1A1rgO3WbCNs',
    appId: '1:968848825333:ios:5513660c8b001078b45ebc',
    messagingSenderId: '968848825333',
    projectId: 'interview-task-project-97e2d',
    storageBucket: 'interview-task-project-97e2d.appspot.com',
    iosBundleId: 'com.example.interviewTaskProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTc-FI5QJvobFGWcyJ28O1A1rgO3WbCNs',
    appId: '1:968848825333:ios:5513660c8b001078b45ebc',
    messagingSenderId: '968848825333',
    projectId: 'interview-task-project-97e2d',
    storageBucket: 'interview-task-project-97e2d.appspot.com',
    iosBundleId: 'com.example.interviewTaskProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfI_VmjnXj1fur9IdwobzmNgGnBlePvl0',
    appId: '1:968848825333:web:91942e5439fb857fb45ebc',
    messagingSenderId: '968848825333',
    projectId: 'interview-task-project-97e2d',
    authDomain: 'interview-task-project-97e2d.firebaseapp.com',
    storageBucket: 'interview-task-project-97e2d.appspot.com',
    measurementId: 'G-VLM0LH9JXD',
  );
}
